// src/docker/data/dockerCommandReference.ts
import { DOCKER_14_TOPICS, DOCKER_UNIVERSAL_CONCEPTS, UniversalDockerConcept } from './unifiedDockerData';

export interface CommandSearchResult {
  command: string;
  description: string;
  conceptId: string;
  conceptTitle: string;
  topicNumber: string;
  topicTitle: string;
  score: number;
  matchedKeywords: string[];
}

interface NaturalLanguagePattern {
  phrases: string[];
  conceptId: string;
  command: string;
  description: string;
}

const NATURAL_LANGUAGE_PATTERNS: NaturalLanguagePattern[] = [
  {
    phrases: ['run a container', 'start a container', 'launch container', 'spin up container', 'create and start'],
    conceptId: 'c-docker-run-basic',
    command: 'docker run -d --name <name> -p <host:cont> <image>',
    description: 'Create and run a new container from an image in detached background mode.',
  },
  {
    phrases: ['stop container', 'halt container', 'shut down container', 'pause container'],
    conceptId: 'c-docker-stop-start',
    command: 'docker stop <container>',
    description: 'Gracefully stop one or more running containers via SIGTERM with SIGKILL fallback.',
  },
  {
    phrases: ['delete container', 'remove container', 'destroy container', 'clean container', 'rm container'],
    conceptId: 'c-docker-rm',
    command: 'docker rm -f <container>',
    description: 'Remove one or more stopped or running (-f) container instances from the host.',
  },
  {
    phrases: ['see containers', 'list containers', 'show running containers', 'view containers', 'check containers'],
    conceptId: 'c-cli-containers',
    command: 'docker ps -a',
    description: 'List all running and exited containers with status, ports, and names.',
  },
  {
    phrases: ['see images', 'list images', 'show images', 'view images', 'check images', 'local images'],
    conceptId: 'c-cli-images',
    command: 'docker images',
    description: 'List all locally stored Docker images with repository, tag, image ID, and size.',
  },
  {
    phrases: ['map a port', 'port forwarding', 'expose port', 'publish port', 'open port to browser'],
    conceptId: 'c-docker-run-flags',
    command: 'docker run -p <host_port>:<container_port> <image>',
    description: 'Publish a container port to the host operating system so web browsers can connect.',
  },
  {
    phrases: ['save data', 'persist data', 'persist database', 'create volume', 'keep data after restart'],
    conceptId: 'c-volume-mounts',
    command: 'docker volume create <name> && docker run -v <name>:<path> <image>',
    description: 'Create and mount a persistent Docker named volume that survives container restarts and deletion.',
  },
  {
    phrases: ['bind mount', 'mount local directory', 'sync folder', 'live edit code', 'hot reload code'],
    conceptId: 'c-bind-mounts',
    command: 'docker run -v $(pwd):/app <image>',
    description: 'Mount a host directory into the container for live source code editing during development.',
  },
  {
    phrases: ['connect containers', 'link containers', 'container networking', 'make containers talk', 'create network'],
    conceptId: 'c-cli-networks',
    command: 'docker network create <net-name> && docker network connect <net-name> <container>',
    description: 'Create a custom bridge network allowing containers to communicate using automatic DNS names.',
  },
  {
    phrases: ['build image', 'compile dockerfile', 'create image', 'make image from dockerfile'],
    conceptId: 'c-dockerfiles',
    command: 'docker build -t <tag> .',
    description: 'Build a new container image from a Dockerfile using the specified build context.',
  },
  {
    phrases: ['upload image', 'push image', 'publish image to hub', 'send image to registry'],
    conceptId: 'c-dockerhub',
    command: 'docker push <username>/<repo>:<tag>',
    description: 'Upload a local image repository to Docker Hub or an external container registry.',
  },
  {
    phrases: ['download image', 'pull image', 'fetch image from hub', 'get image'],
    conceptId: 'c-dockerhub',
    command: 'docker pull <image>:<tag>',
    description: 'Download an image manifest and layers from a container registry to local storage.',
  },
  {
    phrases: ['see logs', 'view logs', 'check logs', 'stream logs', 'container output', 'print stdout'],
    conceptId: 'c-container-logs',
    command: 'docker logs -f --tail 100 <container>',
    description: 'Fetch and stream (-f) the live stdout and stderr logs generated by a container process.',
  },
  {
    phrases: ['debug container', 'interactive shell', 'enter container', 'bash inside container', 'exec into container'],
    conceptId: 'c-docker-exec',
    command: 'docker exec -it <container> sh',
    description: 'Open an interactive pseudo-TTY terminal shell inside an active running container.',
  },
  {
    phrases: ['clean unused images', 'prune images', 'remove dangling images', 'free up disk space'],
    conceptId: 'c-cli-images',
    command: 'docker image prune -a',
    description: 'Delete all unused, dangling, and unreferenced Docker images to reclaim host disk storage.',
  },
  {
    phrases: ['run multiple services', 'start compose', 'orchestrate services', 'docker-compose up', 'start stack'],
    conceptId: 'c-docker-compose',
    command: 'docker compose up -d',
    description: 'Build, create, start, and link multi-container applications declared in a compose.yaml file.',
  },
  {
    phrases: ['scan vulnerabilities', 'security scan', 'cve audit', 'check security flaws'],
    conceptId: 'c-image-security',
    command: 'trivy image <image>',
    description: 'Scan image layers for known CVE vulnerabilities in operating system and application dependencies.',
  },
  {
    phrases: ['resource usage', 'cpu and memory', 'container stats', 'monitor performance'],
    conceptId: 'c-container-inspect-stats',
    command: 'docker stats',
    description: 'Display a live streaming resource usage statistics dashboard for all active containers.',
  },
  {
    phrases: ['database container', 'run postgres', 'run redis', 'spin up mysql'],
    conceptId: 'c-running-databases',
    command: 'docker run -d --name db -e POSTGRES_PASSWORD=<pw> -v pgdata:/var/lib/postgresql/data postgres',
    description: 'Launch official database containers with persistent storage and environment configuration.',
  },
  {
    phrases: ['disposable container', 'one-off command', 'temporary alpine', 'test utility', 'remove after exit'],
    conceptId: 'c-cli-utilities',
    command: 'docker run --rm -it alpine sh',
    description: 'Run a disposable diagnostic utility container that automatically deletes itself upon exiting.',
  },
  {
    phrases: ['swarm cluster', 'docker swarm', 'swarm init', 'orchestrate replicas'],
    conceptId: 'c-docker-swarm',
    command: 'docker swarm init',
    description: 'Initialize a native Docker Swarm cluster manager to coordinate container services across nodes.',
  },
  {
    phrases: ['kubernetes pod', 'deploy to k8s', 'transition to kubernetes', 'k8s deployment'],
    conceptId: 'c-kubernetes-intro',
    command: 'kubectl apply -f deployment.yaml',
    description: 'Transition single-host Docker containers into distributed Kubernetes Pods and Deployments.',
  },
];

export function searchDockerCommands(query: string): CommandSearchResult[] {
  const clean = query.toLowerCase().trim();
  if (!clean) return [];

  const results: CommandSearchResult[] = [];
  const seenConcepts = new Set<string>();

  // 1. Direct Pattern Matching
  for (const pat of NATURAL_LANGUAGE_PATTERNS) {
    let matched = false;
    const matchedKeywords: string[] = [];

    for (const phrase of pat.phrases) {
      if (clean.includes(phrase) || phrase.includes(clean)) {
        matched = true;
        matchedKeywords.push(phrase);
      }
    }

    // Keyword word token overlap
    const queryTokens = clean.split(/\s+/).filter(Boolean);
    const phraseTokens = pat.phrases.flatMap((p) => p.split(/\s+/));
    const tokenMatches = queryTokens.filter((qt) => phraseTokens.includes(qt));
    if (tokenMatches.length >= 2) {
      matched = true;
      matchedKeywords.push(...tokenMatches);
    }

    if (matched && !seenConcepts.has(pat.conceptId)) {
      seenConcepts.add(pat.conceptId);
      const parentTopic = DOCKER_14_TOPICS.find((t) => t.concepts.some((c) => c.id === pat.conceptId));
      const concept = parentTopic?.concepts.find((c) => c.id === pat.conceptId);

      results.push({
        command: pat.command,
        description: pat.description,
        conceptId: pat.conceptId,
        conceptTitle: concept?.title || pat.conceptId,
        topicNumber: parentTopic?.number || '01',
        topicTitle: parentTopic?.title || 'Basics of Docker',
        score: 100 + matchedKeywords.length * 10,
        matchedKeywords,
      });
    }
  }

  // 2. Fallback search across all 42 concepts in DOCKER_14_TOPICS
  for (const topic of DOCKER_14_TOPICS) {
    for (const concept of topic.concepts) {
      if (seenConcepts.has(concept.id)) continue;

      const titleMatch = concept.title.toLowerCase().includes(clean);
      const cmdMatch = concept.command.toLowerCase().includes(clean);
      const descMatch = concept.shortDesc.toLowerCase().includes(clean);

      if (titleMatch || cmdMatch || descMatch) {
        seenConcepts.add(concept.id);
        results.push({
          command: concept.command,
          description: concept.shortDesc,
          conceptId: concept.id,
          conceptTitle: concept.title,
          topicNumber: topic.number,
          topicTitle: topic.title,
          score: titleMatch ? 80 : cmdMatch ? 70 : 50,
          matchedKeywords: [clean],
        });
      }
    }
  }

  return results.sort((a, b) => b.score - a.score);
}
